baseurl = "https://gohugo.io/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
disableLanguages = ["fr"]

[languages.en]
languageName = "English"
weight = 1
title = "Hugo Themes"

[languages.fr]
languageName = "Français"
weight = 2
title = "Thèmes Hugo"

[menu]

  [[menu.main]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "post/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"
    weight = 10