[build]
  publish = "exampleSite/public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.88.1"
  TZ = "America/Toronto"
  HUGO_MODULE_REPLACEMENTS = "github.com/danielfdickinson/adityatelange-hugo-PaperMod -> ../../../repo"
#  GIT_LFS_ENABLED = "1"
#  GIT_LFS_FETCH_INCLUDE = "*.jpg,*.png,*.jpeg,*.svg,*.gif,*.pdf,*.mp4,*.bmp,*.webp,*.ico"

[context.production]
  command = "_scripts/hugo-build \"$URL\""

[context.deploy-preview]
  command = "_scripts/hugo-build \"$DEPLOY_PRIME_URL\""

[context.branch-deploy]
  command = "_scripts/hugo-build \"$DEPLOY_PRIME_URL\""

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[plugins]]
  package = "netlify-plugin-html-validate"

[[plugins]]
  package = "netlify-plugin-checklinks"

    [plugins.inputs]
      checkExternal = false
      skipPatterns = [ "<link rel=\"alternate\"", "<meta http-equiv=\"refresh\" content=\"0; url=", "<link rel=\"icon\"", "<link rel=\"apple-touch-icon\"", "<meta property=\"og:", "<meta property=\"twitter:" ]

[[plugins]]
  package = "netlify-plugin-minify-html"

    [plugins.inputs.minifierOptions]
    collapseBooleanAttributes = true
    decodeEntities = true
    preserveLineBreaks = true
    removeAttributeQuotes = false
    removeComments = true
    removeEmptyAttributes = true
    removeOptionalTags = false
    removeRedundantAttributes = true
    removeScriptTypeAttributes = true
    removeTypeLinkTypeAttributes = true
    useShortDocType = false

[dev]
  command = "_scripts/hugo-serve"
  targetPort = 1313
  framework = "#custom"
